[server]
address = "localhost" # Address to connect to the server on
port = 42674 # Port to connect to the server on
retries = 0 # Number of times to retry connecting to the server, set to 0 for unlimited retries
autoconnect = true # Automatically connect to the server on startup (true/false)
password = "" # Password to use when connecting to the server (leave blank for no password "")

[window]
size = [ 0, 0 ] # [width, height] in pixels # Set to 0, 0 to use borderless window
location = [ 0, 0 ] # [x, y] in pixels

[map]
# Current Included default maps are:
#   KTO - Korea
#   Balkans - Balkans
#   Israel - Israel
#   MidEast - Middle East 128
# Feel free to contribute with new map 4k textures and they can be added to the release
theatre = "KTO" # Theatre to load the map for on startup
map_alpha = 100 # 0-255 # Alpha value for the map, the lower the value the more transparent the map will be
background_color = [ 50, 50, 50 ] # [r, g, b] # Background color for the map
# Colors that want to be switched from the Tacview default to a custom value, for better visibility.
# Accepts the format [defaultcolor, newcolor], where the first arguments is a color String, and the second a color String or [r, g, b] array
unit_color_switching = [
    ["Blue", [0, 225, 255]]
]