# This is a basic workflow to help you get started with Actions

name: Build exe

# Controls when the action will run.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Build binaries
        run: pyinstaller OpenRadar.spec

      - name: Rename exe
        run: cp dist/OpenRadar.exe dist/OpenRadar_${{  github.ref_name }}.exe
        if: startsWith(github.ref, 'refs/tags/v')

      - uses: actions/upload-artifact@v4
        with:
          name: OpenRadar_${{  github.ref_name }}.exe
          path: dist/OpenRadar_${{  github.ref_name }}.exe
        if: startsWith(github.ref, 'refs/tags/v')

      - uses: actions/upload-artifact@v4
        with:
          name: OpenRadar.exe
          path: dist/OpenRadar.exe
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            dist/OpenRadar_${{  github.ref_name }}.exe
